<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="natalia-All-Series" name="Аттестация" tests="6" failures="1" timestamp="21 Oct 2015 08:39:08 GMT" time="363.778" errors="0">
  <testcase name="testAddFact" time="55.36" classname="myobject.Certification"/>
  <testcase name="testAddPlan" time="33.382" classname="myobject.Certification"/>
  <testcase name="testEditFact" time="59.62" classname="myobject.Certification"/>
  <testcase name="testEditPlan" time="35.8" classname="myobject.Certification"/>
  <testcase name="testPlanToFact" time="40.816" classname="myobject.Certification"/>
  <testcase name="testDelete" time="23.176" classname="myobject.Certification">
    <failure type="java.lang.AssertionError" message="Аттестация не удалена!">
      <![CDATA[java.lang.AssertionError: Аттестация не удалена!
	at myobject.Certification.testDelete(Certification.java:153)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDelete -->
</testsuite> <!-- Аттестация -->
